name: Docker Image CI Back-End

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run : |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Afficher la derniÃ¨re version de l'image Docker
        run: echo $(curl -s https://registry.hub.docker.com/v2/repositories/lucasmoreno82/back-nodejs/tags/?page_size=1 | jq -r '.results[].name')
      # - name: Increment version
      #   run: echo ${{env.IMAGE_VERSION%.*}}.$((${env.IMAGE_VERSION##*.}+1)) >> $GITHUB_ENV

      # - name: Checkout the repository that contains Dockerfile
      #   uses: actions/checkout@v3
      #   with:
      #     repository: Lucas-Moreno/back-nodejs
      #     ref: main
      # - name: docker build
      #   run: docker build . --file /home/runner/work/archi-project/archi-project/Dockerfile --tag lucasmoreno82/back-nodejs:${{ env.IMAGE_VERSION }}
          
      # - name: docker tag
      #   run: docker tag ${{secrets.DOCKER_USER}}/back-nodejs:${{ env.IMAGE_VERSION }} ${{secrets.DOCKER_USER}}/back-nodejs:$(date +%s)

      # - name: docker push
      #   run: docker push ${{secrets.DOCKER_USER}}/back-nodejs:${{ env.IMAGE_VERSION }}